// packages/vue/src/components/PlaygroundToolbar.vue
<template>
  <div class="playground-toolbar">
    <button :disabled="status !== 'ready'" @click="saveSnapshot">Save</button>
    <div class="status-indicator" :data-status="status">
      <template v-if="status === 'ready'">✓ Ready</template>
      <template v-else-if="status === 'initializing'">⏳ Initializing...</template>
      <template v-else-if="status === 'installing'">📦 Installing...</template>
      <template v-else-if="status === 'error'">❌ Error</template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { usePlaygroundContext } from '../context/PlaygroundContext'

const { saveSnapshot, status } = usePlaygroundContext()
</script>

// packages/react/src/components/PlaygroundToolbar.tsx
import { usePlaygroundContext } from '../context/PlaygroundContext';

export function PlaygroundToolbar() {
  const { saveSnapshot, status } = usePlaygroundContext();

  return (
    <div className="playground-toolbar">
      <button onClick={saveSnapshot} disabled={status !== 'ready'}>
        Save
      </button>
      <div className="status-indicator" data-status={status}>
        {status === 'ready' && '✓ Ready'}
        {status === 'initializing' && '⏳ Initializing...'}
        {status === 'installing' && '📦 Installing...'}
        {status === 'error' && '❌ Error'}
      </div>
    </div>
  );
}
