// packages/react/src/components/PlaygroundTerminal.tsx
import { useEffect, useRef } from 'react'
import { usePlaygroundContext } from '../context/PlaygroundContext'

export function PlaygroundTerminal() {
  const { engine, status } = usePlaygroundContext()
  const containerRef = useRef<HTMLDivElement>(null)
  const mountedEngineRef = useRef<typeof engine>(null)

  useEffect(() => {
    if (
      containerRef.current
      && engine
      && status === 'ready'
      && mountedEngineRef.current !== engine
    ) {
      mountedEngineRef.current = engine
      engine.mountTerminal(containerRef.current)
    }

    return () => {
      // When engine reference changes, reset so the new engine gets a fresh mount
      if (mountedEngineRef.current !== engine) {
        mountedEngineRef.current = null
      }
    }
  }, [engine, status])

  return (
    <div className="playground-terminal">
      <div className="terminal-header">Console</div>
      <div ref={containerRef} className="terminal-content" />
    </div>
  )
}

// packages/vue/src/components/PlaygroundTerminal.vue
<script setup lang="ts">
import type { PlaygroundEngine } from '@setemiojo/playground-core'
import { ref, watch } from 'vue'
import { usePlaygroundContext } from '../context/PlaygroundContext'

const { engine, status } = usePlaygroundContext()
const containerRef = ref<HTMLDivElement | null>(null)
// Tracks which engine instance has been mounted to avoid double-mounting
const mountedEngine = ref<PlaygroundEngine | null>(null)

watch(
  [containerRef, engine, status],
  ([container, eng, s]) => {
    if (container && eng && s === 'ready' && mountedEngine.value !== eng) {
      mountedEngine.value = eng
      eng.mountTerminal(container)
    }
  },
  { flush: 'post' },
)

// Reset on engine change so the new instance gets mounted when ready
watch(engine, () => {
  mountedEngine.value = null
})
</script>

<template>
  <div class="playground-terminal">
    <div class="terminal-header">
      Console
    </div>
    <div ref="containerRef" class="terminal-content" />
  </div>
</template>
