// packages/react/src/components/PlaygroundFileTree.tsx
import type { FileNode } from '@setemiojo/playground-core'
import { useMemo } from 'react'
import { usePlaygroundContext } from '../context/PlaygroundContext'

interface FileTreeNodeProps {
  node: FileNode
  onFileClick: (path: string) => void
  hiddenFiles: string[]
}

/**
 * Check if a path should be hidden
 */
function isHidden(path: string, hiddenFiles: string[]): boolean {
  // Normalize path to always start with /
  const normalizedPath = path.startsWith('/') ? path : `/${path}`
  return hiddenFiles.some((hidden) => {
    const normalizedHidden = hidden.startsWith('/') ? hidden : `/${hidden}`
    return normalizedPath === normalizedHidden
  })
}

/**
 * Recursively filter out hidden files from a file tree
 */
function filterHiddenFiles(nodes: FileNode[], hiddenFiles: string[]): FileNode[] {
  if (!hiddenFiles.length) return nodes

  return nodes
    .filter(node => !isHidden(node.path, hiddenFiles))
    .map((node) => {
      if (node.type === 'directory' && node.children) {
        return {
          ...node,
          children: filterHiddenFiles(node.children, hiddenFiles),
        }
      }
      return node
    })
    // Filter out empty directories after filtering children
    .filter(node => node.type === 'file' || (node.children && node.children.length > 0))
}

function FileTreeNode({ node, onFileClick, hiddenFiles }: FileTreeNodeProps) {
  if (node.type === 'file') {
    return (
      <div className="file-node" onClick={() => onFileClick(node.path)}>
        <span className="file-icon">📄</span>
        <span className="file-name">{node.name}</span>
      </div>
    )
  }

  return (
    <details className="directory-node" open>
      <summary>
        <span className="folder-icon">📁</span>
        <span className="folder-name">{node.name}</span>
      </summary>
      <div className="directory-children">
        {node.children?.map((child: FileNode) => (
          <FileTreeNode
            key={child.path}
            node={child}
            onFileClick={onFileClick}
            hiddenFiles={hiddenFiles}
          />
        ))}
      </div>
    </details>
  )
}

const SKELETON_WIDTHS = ['60%', '45%', '72%', '38%', '55%', '65%', '42%']

function FileTreeSkeleton() {
  return (
    <div className="file-tree-skeleton" aria-label="Loading files…" aria-busy="true">
      {SKELETON_WIDTHS.map((w, i) => (
        <div key={i} className="file-tree-skeleton-row" style={{ paddingLeft: i > 1 ? 22 : 8 }}>
          <div className="file-tree-skeleton-icon" />
          <div className="file-tree-skeleton-label" style={{ width: w }} />
        </div>
      ))}
    </div>
  )
}

export function PlaygroundFileTree() {
  const { files, openFile, status, hiddenFiles } = usePlaygroundContext()
  const isLoading = status === 'initializing' || status === 'installing' || files.length === 0

  // Filter out hidden files
  const visibleFiles = useMemo(
    () => filterHiddenFiles(files, hiddenFiles),
    [files, hiddenFiles],
  )

  return (
    <div className="playground-file-tree">
      <div className="file-tree-header">
        Files
        {isLoading && <span className="file-tree-spinner" aria-hidden="true" />}
      </div>
      <div className="file-tree-content">
        {isLoading
          ? <FileTreeSkeleton />
          : visibleFiles.map(node => (
              <FileTreeNode
                key={node.path}
                node={node}
                onFileClick={openFile}
                hiddenFiles={hiddenFiles}
              />
            ))}
      </div>
    </div>
  )
}

// packages/vue/src/components/PlaygroundFileTree.vue
<script setup lang="ts">
import type { FileNode } from '@setemiojo/playground-core'
import { computed } from 'vue'
import { usePlaygroundContext } from '../context/PlaygroundContext'
import FileTreeNode from './FileTreeNode.vue'
import FileTreeSkeleton from './FileTreeSkeleton.vue'

const { files, openFile, status, hiddenFiles } = usePlaygroundContext()

const isLoading = computed(() => status.value === 'initializing' || status.value === 'installing')

function filterHidden(nodes: readonly FileNode[], hidden: string[]): FileNode[] {
  if (!hidden.length)
    return [...nodes]
  return nodes
    .filter(node => !hidden.some((h) => {
      const np = node.path.startsWith('/') ? node.path : `/${node.path}`
      const nh = h.startsWith('/') ? h : `/${h}`
      return np === nh
    }))
    .map(node =>
      node.type === 'directory' && node.children
        ? { ...node, children: filterHidden(node.children, hidden) }
        : { ...node },
    )
    .filter(node => node.type === 'file' || (node.children && node.children.length > 0))
}

// .value needed in <script> but not in <template> — Vue auto-unwraps refs in templates
const visibleFiles = computed(() => filterHidden(files.value as readonly FileNode[], hiddenFiles.value))
</script>

<template>
  <div class="playground-file-tree">
    <div class="file-tree-header">
      Files
      <span v-if="isLoading" class="file-tree-spinner" aria-hidden="true" />
    </div>
    <div class="file-tree-content">
      <FileTreeSkeleton v-if="isLoading" />
      <FileTreeNode
        v-for="node in visibleFiles"
        v-else
        :key="node.path"
        :node="node"
        :hidden-files="hiddenFiles"
        @file-click="openFile"
      />
    </div>
  </div>
</template>
