// packages/react/src/components/PlaygroundEditor.tsx
import { useEffect, useRef } from 'react'
import { usePlaygroundContext } from '../context/PlaygroundContext'

function SwitchingIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M21 2H3v16h5v4l4-4h5l4-4V2zM11 11V7M15 11V7" />
    </svg>
  )
}

export function PlaygroundEditor() {
  const { engine, status, template } = usePlaygroundContext()
  const containerRef = useRef<HTMLDivElement>(null)
  const mountedRef = useRef(false)
  const prevStatusRef = useRef(status)

  // Reset mountedRef whenever status leaves 'ready' (template switch or re-init)
  // so that when status returns to 'ready', mountEditor runs again with the new files.
  useEffect(() => {
    if (prevStatusRef.current === 'ready' && status !== 'ready') {
      mountedRef.current = false
    }
    prevStatusRef.current = status
  }, [status])

  useEffect(() => {
    mountedRef.current = false
  }, [engine])

  useEffect(() => {
    if (containerRef.current && engine && status === 'ready' && !mountedRef.current) {
      mountedRef.current = true
      engine.mountEditor(containerRef.current).catch((error) => {
        console.error('Failed to mount editor:', error)
        mountedRef.current = false
      })
    }
  }, [engine, status])

  const isSwitching = status === 'initializing' || status === 'installing'

  const switchingLabel = status === 'installing'
    ? `Installing ${template?.name ?? ''} dependencies…`
    : `Switching to ${template?.name ?? ''}…`

  return (
    <div className="playground-editor">
      <div ref={containerRef} className="editor-container" />
      {isSwitching && (
        <div className="editor-switching-overlay" aria-live="polite" aria-label={switchingLabel}>
          <div className="editor-switching-card">
            <span className="editor-switching-icon"><SwitchingIcon /></span>
            <span className="editor-switching-label">{switchingLabel}</span>
            <span className="editor-switching-dots">
              <span />
              <span />
              <span />
            </span>
          </div>
        </div>
      )}
    </div>
  )
}

// packages/vue/src/components/PlaygroundEditor.vue
<template>
  <div class="playground-editor">
    <div ref="containerRef" class="editor-container" />
    <div
      v-if="isSwitching"
      class="editor-switching-overlay"
      :aria-label="switchingLabel"
      aria-live="polite"
    >
      <div class="editor-switching-card">
        <span class="editor-switching-icon">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M21 2H3v16h5v4l4-4h5l4-4V2zM11 11V7M15 11V7" />
          </svg>
        </span>
        <span class="editor-switching-label">{{ switchingLabel }}</span>
        <span class="editor-switching-dots"><span /><span /><span /></span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { usePlaygroundContext } from '../context/PlaygroundContext'

const { engine, status, template } = usePlaygroundContext()
const containerRef = ref<HTMLDivElement | null>(null)
const mounted = ref(false)

watch(status, (next, prev) => {
  if (prev === 'ready' && next !== 'ready') mounted.value = false
})

watch(engine, () => { mounted.value = false })

watch(
  [containerRef, engine, status],
  ([container, eng, s]) => {
    if (container && eng && s === 'ready' && !mounted.value) {
      mounted.value = true
      eng.mountEditor(container).catch((err: Error) => {
        console.error('Failed to mount editor:', err)
        mounted.value = false
      })
    }
  },
  { flush: 'post' },
)

// In templates, refs are auto-unwrapped — no .value needed in <template> blocks
const isSwitching = computed(() => status.value === 'initializing' || status.value === 'installing')

const switchingLabel = computed(() =>
  status.value === 'installing'
    ? `Installing ${template.value?.name ?? ''} dependencies…`
    : `Switching to ${template.value?.name ?? ''}…`,
)
</script>
