// packages/react/src/components/PlaygroundPreview.tsx
import { useEffect, useRef, useState } from 'react'
import { usePlaygroundContext } from '../context/PlaygroundContext'

export interface PlaygroundPreviewProps {
  title?: string
}

function RefreshIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <polyline points="23 4 23 10 17 10" />
      <polyline points="1 20 1 14 7 14" />
      <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
    </svg>
  )
}

function ExternalLinkIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
      <polyline points="15 3 21 3 21 9" />
      <line x1="10" y1="14" x2="21" y2="3" />
    </svg>
  )
}

export function PlaygroundPreview({ title = 'Preview' }: PlaygroundPreviewProps) {
  const { engine, previewUrl, status } = usePlaygroundContext()
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const lastUrlRef = useRef<string | null>(null)
  const lastEngineRef = useRef<typeof engine>(null)
  const [inputUrl, setInputUrl] = useState('')
  const [iframeLoading, setIframeLoading] = useState(false)

  // Keep input in sync when the server URL changes (new template boot or switch)
  useEffect(() => {
    if (previewUrl) {
      setInputUrl(previewUrl)
      setIframeLoading(true)
    }
  }, [previewUrl])

  useEffect(() => {
    const shouldMount = iframeRef.current
      && engine
      && previewUrl
      && (previewUrl !== lastUrlRef.current || engine !== lastEngineRef.current)

    if (shouldMount && iframeRef.current) {
      engine.mountPreview(iframeRef.current)
      lastUrlRef.current = previewUrl
      lastEngineRef.current = engine
    }
  }, [engine, previewUrl])

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!iframeRef.current || !inputUrl)
      return
    setIframeLoading(true)
    iframeRef.current.src = inputUrl
  }

  function handleRefresh() {
    if (!iframeRef.current)
      return
    setIframeLoading(true)
    // Reassigning src triggers a reload without needing contentWindow access
    // (which is blocked cross-origin for WebContainer preview URLs)
    // eslint-disable-next-line no-self-assign
    iframeRef.current.src = iframeRef.current.src
  }

  const isReady = status === 'ready' && !!previewUrl

  return (
    <div className="playground-preview">
      <div className="preview-toolbar">
        <span className="preview-title">{title}</span>

        <form className="preview-url-form" onSubmit={handleSubmit}>
          <div className="preview-url-bar">
            {iframeLoading && isReady
              ? <span className="preview-spinner" aria-hidden="true" />
              : <span className="preview-dot" aria-hidden="true" data-ready={isReady} />}
            <input
              type="text"
              className="preview-url-input"
              value={inputUrl}
              onChange={e => setInputUrl(e.target.value)}
              disabled={!isReady}
              spellCheck={false}
              aria-label="Preview URL"
              placeholder="Waiting for server…"
            />
          </div>
        </form>

        <button
          type="button"
          className="preview-icon-btn"
          onClick={handleRefresh}
          disabled={!isReady}
          title="Refresh preview"
          aria-label="Refresh preview"
        >
          <RefreshIcon />
        </button>

        <button
          type="button"
          className="preview-icon-btn"
          onClick={() => window.open(inputUrl || previewUrl || '', '_blank')}
          disabled={!isReady}
          title="Open in new tab"
          aria-label="Open in new tab"
        >
          <ExternalLinkIcon />
        </button>
      </div>

      <div className="preview-frame-area">
        {status !== 'ready' && (
          <div className="loading">
            {status === 'initializing' && 'Initializing…'}
            {status === 'installing' && 'Installing dependencies…'}
            {status === 'error' && 'Error loading preview'}
          </div>
        )}
        <iframe
          ref={iframeRef}
          title={title}
          onLoad={() => setIframeLoading(false)}
          style={{ display: previewUrl ? 'block' : 'none' }}
        />
      </div>
    </div>
  )
}

// packages/vue/src/components/PlaygroundPreview.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { usePlaygroundContext } from '../context/PlaygroundContext'

withDefaults(defineProps<{ title?: string }>(), { title: 'Preview' })

const { engine, previewUrl, status } = usePlaygroundContext()

const iframeRef = ref<HTMLIFrameElement | null>(null)
const inputUrl = ref('')
const iframeLoading = ref(false)
const lastUrl = ref<string | null>(null)
const lastEngine = ref(engine.value)

// .value required in <script> for ref access; templates auto-unwrap
const isReady = computed(() => status.value === 'ready' && !!previewUrl.value)

watch(previewUrl, (url) => {
  if (url) {
    inputUrl.value = url
    iframeLoading.value = true
  }
})

watch([engine, previewUrl], ([eng, url]) => {
  const shouldMount = iframeRef.value && eng && url
    && (url !== lastUrl.value || eng !== lastEngine.value)
  if (shouldMount && iframeRef.value) {
    eng!.mountPreview(iframeRef.value)
    lastUrl.value = url!
    lastEngine.value = eng
  }
}, { flush: 'post' })

function handleSubmit() {
  if (!iframeRef.value || !inputUrl.value)
    return
  iframeLoading.value = true
  iframeRef.value.src = inputUrl.value
}

function handleRefresh() {
  if (!iframeRef.value)
    return
  iframeLoading.value = true
  // eslint-disable-next-line no-self-assign
  iframeRef.value.src = iframeRef.value.src
}

function openNewTab() {
  window.open(inputUrl.value || previewUrl.value || '', '_blank')
}
</script>

<template>
  <div class="playground-preview">
    <div class="preview-toolbar">
      <span class="preview-title">{{ title }}</span>

      <form class="preview-url-form" @submit.prevent="handleSubmit">
        <div class="preview-url-bar">
          <span v-if="iframeLoading && isReady" class="preview-spinner" aria-hidden="true" />
          <span v-else class="preview-dot" :data-ready="isReady" aria-hidden="true" />
          <input
            v-model="inputUrl"
            type="text"
            class="preview-url-input"
            :disabled="!isReady"
            spellcheck="false"
            aria-label="Preview URL"
            placeholder="Waiting for server…"
          >
        </div>
      </form>

      <button type="button" class="preview-icon-btn" :disabled="!isReady" title="Refresh preview" aria-label="Refresh preview" @click="handleRefresh">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <polyline points="23 4 23 10 17 10" /><polyline points="1 20 1 14 7 14" />
          <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
        </svg>
      </button>

      <button type="button" class="preview-icon-btn" :disabled="!isReady" title="Open in new tab" aria-label="Open in new tab" @click="openNewTab">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
          <polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" />
        </svg>
      </button>
    </div>

    <div class="preview-frame-area">
      <div v-if="status !== 'ready'" class="loading">
        <template v-if="status === 'initializing'">
          Initializing…
        </template>
        <template v-else-if="status === 'installing'">
          Installing dependencies…
        </template>
        <template v-else-if="status === 'error'">
          Error loading preview
        </template>
      </div>
      <iframe
        ref="iframeRef"
        :title="title"
        :style="{ display: previewUrl ? 'block' : 'none' }"
        @load="iframeLoading = false"
      />
    </div>
  </div>
</template>
