// packages/react/src/components/ResizablePanel.tsx
import type { CSSProperties, ReactNode } from 'react'
import {
  useCallback,
  useEffect,
  useRef,
  useState,
} from 'react'
import { useIsMobile } from '../hooks/useMediaQuery'

export interface ResizablePanelProps {
  /** Left or top panel content */
  firstPanel: ReactNode
  /** Right or bottom panel content */
  secondPanel: ReactNode
  /** Direction of the split */
  direction?: 'horizontal' | 'vertical'
  /** Enable responsive behavior - switches to vertical on mobile */
  responsive?: boolean
  /** Breakpoint for responsive switch in pixels (default: 768) */
  responsiveBreakpoint?: number
  /** Initial size of the first panel as a percentage (0-100) */
  initialSize?: number
  /** Initial size for mobile/vertical layout (default: 40) */
  mobileInitialSize?: number
  /** Minimum size of the first panel as a percentage */
  minSize?: number
  /** Maximum size of the first panel as a percentage */
  maxSize?: number
  /** Storage key for persisting the panel size */
  storageKey?: string
  /** Class name for the container */
  className?: string
  /** Class name for the first panel */
  firstPanelClassName?: string
  /** Class name for the second panel */
  secondPanelClassName?: string
  /** Class name for the resizer handle */
  resizerClassName?: string
  /** Callback when resize starts */
  onResizeStart?: () => void
  /** Callback during resize with current size percentage */
  onResize?: (size: number) => void
  /** Callback when resize ends with final size percentage */
  onResizeEnd?: (size: number) => void
}

export function ResizablePanel({
  firstPanel,
  secondPanel,
  direction = 'horizontal',
  responsive = false,
  responsiveBreakpoint = 768,
  initialSize = 50,
  mobileInitialSize = 40,
  minSize = 10,
  maxSize = 90,
  storageKey,
  className = '',
  firstPanelClassName = '',
  secondPanelClassName = '',
  resizerClassName = '',
  onResizeStart,
  onResize,
  onResizeEnd,
}: ResizablePanelProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const isMobile = useIsMobile(responsiveBreakpoint)

  // Determine effective direction based on responsive prop
  const effectiveDirection = responsive && isMobile ? 'vertical' : direction
  const isHorizontal = effectiveDirection === 'horizontal'

  // Use different storage keys for mobile vs desktop to preserve both sizes
  const effectiveStorageKey = storageKey
    ? `${storageKey}${responsive && isMobile ? '-mobile' : ''}`
    : undefined

  const [size, setSize] = useState<number>(() => {
    if (effectiveStorageKey && typeof window !== 'undefined') {
      try {
        const stored = localStorage.getItem(effectiveStorageKey)
        if (stored) {
          const parsed = Number.parseFloat(stored)
          if (!Number.isNaN(parsed) && parsed >= minSize && parsed <= maxSize) {
            return parsed
          }
        }
      }
      catch {
        // localStorage might be blocked in sandboxed iframes
      }
    }
    return responsive && isMobile ? mobileInitialSize : initialSize
  })
  const [isDragging, setIsDragging] = useState(false)
  const dragStartRef = useRef<{ position: number, size: number } | null>(null)
  const currentSizeRef = useRef(size)
  currentSizeRef.current = size

  // Update size when switching between mobile and desktop
  useEffect(() => {
    if (!responsive)
      return

    // Load the appropriate size for the current mode
    if (effectiveStorageKey && typeof window !== 'undefined') {
      try {
        const stored = localStorage.getItem(effectiveStorageKey)
        if (stored) {
          const parsed = Number.parseFloat(stored)
          if (!Number.isNaN(parsed) && parsed >= minSize && parsed <= maxSize) {
            setSize(parsed)
            return
          }
        }
      }
      catch {
        // localStorage might be blocked in sandboxed iframes
      }
    }
    // Fall back to default sizes
    setSize(isMobile ? mobileInitialSize : initialSize)
  }, [isMobile, responsive, effectiveStorageKey, minSize, maxSize, mobileInitialSize, initialSize])

  const clampSize = useCallback(
    (value: number) => Math.min(maxSize, Math.max(minSize, value)),
    [minSize, maxSize],
  )

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault()
      setIsDragging(true)
      dragStartRef.current = {
        position: isHorizontal ? e.clientX : e.clientY,
        size,
      }
      onResizeStart?.()
    },
    [isHorizontal, size, onResizeStart],
  )

  const handleTouchStart = useCallback(
    (e: React.TouchEvent) => {
      const touch = e.touches[0]
      setIsDragging(true)
      dragStartRef.current = {
        position: isHorizontal ? touch.clientX : touch.clientY,
        size,
      }
      onResizeStart?.()
    },
    [isHorizontal, size, onResizeStart],
  )

  useEffect(() => {
    if (!isDragging)
      return

    const handleMouseMove = (e: MouseEvent) => {
      if (!containerRef.current || !dragStartRef.current)
        return

      const container = containerRef.current.getBoundingClientRect()
      const containerSize = isHorizontal ? container.width : container.height
      const currentPosition = isHorizontal ? e.clientX : e.clientY
      const startPosition = dragStartRef.current.position
      const delta = currentPosition - startPosition
      const deltaPercent = (delta / containerSize) * 100
      const newSize = clampSize(dragStartRef.current.size + deltaPercent)

      setSize(newSize)
      onResize?.(newSize)
    }

    const handleTouchMove = (e: TouchEvent) => {
      if (!containerRef.current || !dragStartRef.current)
        return

      const touch = e.touches[0]
      const container = containerRef.current.getBoundingClientRect()
      const containerSize = isHorizontal ? container.width : container.height
      const currentPosition = isHorizontal ? touch.clientX : touch.clientY
      const startPosition = dragStartRef.current.position
      const delta = currentPosition - startPosition
      const deltaPercent = (delta / containerSize) * 100
      const newSize = clampSize(dragStartRef.current.size + deltaPercent)

      setSize(newSize)
      onResize?.(newSize)
    }

    const handleEnd = () => {
      setIsDragging(false)
      dragStartRef.current = null
      const finalSize = currentSizeRef.current
      if (effectiveStorageKey) {
        try {
          localStorage.setItem(effectiveStorageKey, finalSize.toString())
        }
        catch {
          // localStorage might be blocked in sandboxed iframes
        }
      }
      onResizeEnd?.(finalSize)
    }

    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseup', handleEnd)
    document.addEventListener('touchmove', handleTouchMove)
    document.addEventListener('touchend', handleEnd)

    return () => {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleEnd)
      document.removeEventListener('touchmove', handleTouchMove)
      document.removeEventListener('touchend', handleEnd)
    }
  }, [isDragging, isHorizontal, clampSize, effectiveStorageKey, onResize, onResizeEnd])

  const containerStyle: CSSProperties = {
    display: 'flex',
    flexDirection: isHorizontal ? 'row' : 'column',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
  }

  const firstPanelStyle: CSSProperties = {
    [isHorizontal ? 'width' : 'height']: `${size}%`,
    flexShrink: 0,
    overflow: 'hidden',
  }

  const secondPanelStyle: CSSProperties = {
    flex: 1,
    overflow: 'hidden',
  }

  const resizerStyle: CSSProperties = {
    [isHorizontal ? 'width' : 'height']: '8px',
    cursor: isHorizontal ? 'col-resize' : 'row-resize',
    background: 'transparent',
    position: 'relative',
    flexShrink: 0,
    zIndex: 10,
  }

  return (
    <div
      ref={containerRef}
      className={`resizable-panel ${className}`}
      style={containerStyle}
      data-direction={effectiveDirection}
      data-dragging={isDragging}
    >
      <div
        className={`resizable-panel-first ${firstPanelClassName}`}
        style={firstPanelStyle}
      >
        {firstPanel}
      </div>
      <div
        className={`resizable-panel-resizer ${resizerClassName}`}
        style={resizerStyle}
        onMouseDown={handleMouseDown}
        onTouchStart={handleTouchStart}
        role="separator"
        aria-orientation={isHorizontal ? 'vertical' : 'horizontal'}
        aria-valuenow={Math.round(size)}
        aria-valuemin={minSize}
        aria-valuemax={maxSize}
        tabIndex={0}
      >
        <div className="resizable-panel-resizer-line" />
      </div>
      <div
        className={`resizable-panel-second ${secondPanelClassName}`}
        style={secondPanelStyle}
      >
        {secondPanel}
      </div>
    </div>
  )
}

// packages/vue/src/components/ResizablePanel.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import { computed, onUnmounted, ref, watch } from 'vue'

const props = withDefaults(defineProps<{
  direction?: 'horizontal' | 'vertical'
  responsive?: boolean
  responsiveBreakpoint?: number
  initialSize?: number
  mobileInitialSize?: number
  minSize?: number
  maxSize?: number
  storageKey?: string
  className?: string
  firstPanelClassName?: string
  secondPanelClassName?: string
  resizerClassName?: string
}>(), {
  direction: 'horizontal',
  responsive: false,
  responsiveBreakpoint: 768,
  initialSize: 50,
  mobileInitialSize: 40,
  minSize: 10,
  maxSize: 90,
  className: '',
  firstPanelClassName: '',
  secondPanelClassName: '',
  resizerClassName: '',
})

const emit = defineEmits<{
  (e: 'resizeStart'): void
  (e: 'resize', size: number): void
  (e: 'resizeEnd', size: number): void
}>()

const containerRef = ref<HTMLDivElement | null>(null)
const isDragging = ref(false)
const isMobile = ref(typeof window !== 'undefined' ? window.innerWidth <= props.responsiveBreakpoint : false)

function clamp(v: number) {
  return Math.min(props.maxSize, Math.max(props.minSize, v))
}

const effectiveDirection = computed(() =>
  props.responsive && isMobile.value ? 'vertical' : props.direction,
)

const isHorizontal = computed(() => effectiveDirection.value === 'horizontal')

const effectiveStorageKey = computed(() =>
  props.storageKey ? `${props.storageKey}${props.responsive && isMobile.value ? '-mobile' : ''}` : undefined,
)

function readStored(key: string | undefined, fallback: number): number {
  if (!key || typeof window === 'undefined')
    return fallback
  try {
    const v = localStorage.getItem(key)
    if (v) {
      const n = Number.parseFloat(v)
      if (!Number.isNaN(n) && n >= props.minSize && n <= props.maxSize)
        return n
    }
  }
  catch { /* sandboxed */ }
  return fallback
}

const size = ref(readStored(
  props.storageKey ? `${props.storageKey}${isMobile.value ? '-mobile' : ''}` : undefined,
  isMobile.value ? props.mobileInitialSize : props.initialSize,
))

// Sync size when orientation switches
watch(isMobile, () => {
  size.value = readStored(
    effectiveStorageKey.value,
    isMobile.value ? props.mobileInitialSize : props.initialSize,
  )
})

// Handle window resize for responsive mode
let resizeHandler: (() => void) | null = null
if (typeof window !== 'undefined') {
  resizeHandler = () => {
    isMobile.value = window.innerWidth <= props.responsiveBreakpoint
  }
  window.addEventListener('resize', resizeHandler)
  onUnmounted(() => {
    if (resizeHandler)
      window.removeEventListener('resize', resizeHandler)
  })
}

// Drag state
let dragStart: { position: number, size: number } | null = null

function handleMouseDown(e: MouseEvent) {
  e.preventDefault()
  isDragging.value = true
  dragStart = { position: isHorizontal.value ? e.clientX : e.clientY, size: size.value }
  emit('resizeStart')
  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onEnd)
}

function handleTouchStart(e: TouchEvent) {
  const touch = e.touches[0]
  isDragging.value = true
  dragStart = { position: isHorizontal.value ? touch.clientX : touch.clientY, size: size.value }
  emit('resizeStart')
  document.addEventListener('touchmove', onTouchMove)
  document.addEventListener('touchend', onEnd)
}

function onMouseMove(e: MouseEvent) {
  if (!containerRef.value || !dragStart)
    return
  const rect = containerRef.value.getBoundingClientRect()
  const containerSize = isHorizontal.value ? rect.width : rect.height
  const delta = (isHorizontal.value ? e.clientX : e.clientY) - dragStart.position
  const newSize = clamp(dragStart.size + (delta / containerSize) * 100)
  size.value = newSize
  emit('resize', newSize)
}

function onTouchMove(e: TouchEvent) {
  if (!containerRef.value || !dragStart)
    return
  const touch = e.touches[0]
  const rect = containerRef.value.getBoundingClientRect()
  const containerSize = isHorizontal.value ? rect.width : rect.height
  const delta = (isHorizontal.value ? touch.clientX : touch.clientY) - dragStart.position
  const newSize = clamp(dragStart.size + (delta / containerSize) * 100)
  size.value = newSize
  emit('resize', newSize)
}

function onEnd() {
  isDragging.value = false
  dragStart = null
  const finalSize = size.value
  if (effectiveStorageKey.value) {
    try {
      localStorage.setItem(effectiveStorageKey.value, finalSize.toString())
    }
    catch { /* sandboxed */ }
  }
  emit('resizeEnd', finalSize)
  document.removeEventListener('mousemove', onMouseMove)
  document.removeEventListener('mouseup', onEnd)
  document.removeEventListener('touchmove', onTouchMove)
  document.removeEventListener('touchend', onEnd)
}

onUnmounted(() => {
  document.removeEventListener('mousemove', onMouseMove)
  document.removeEventListener('mouseup', onEnd)
  document.removeEventListener('touchmove', onTouchMove)
  document.removeEventListener('touchend', onEnd)
})

const containerStyle = computed<CSSProperties>(() => ({
  display: 'flex',
  flexDirection: isHorizontal.value ? 'row' : 'column',
  width: '100%',
  height: '100%',
  overflow: 'hidden',
}))

const firstPanelStyle = computed<CSSProperties>(() => ({
  [isHorizontal.value ? 'width' : 'height']: `${size.value}%`,
  flexShrink: 0,
  overflow: 'hidden',
}))

const secondPanelStyle = computed<CSSProperties>(() => ({
  flex: 1,
  overflow: 'hidden',
}))

const resizerStyle = computed<CSSProperties>(() => ({
  [isHorizontal.value ? 'width' : 'height']: '8px',
  cursor: isHorizontal.value ? 'col-resize' : 'row-resize',
  background: 'transparent',
  position: 'relative',
  flexShrink: 0,
  zIndex: 10,
}))
</script>

<template>
  <div
    ref="containerRef"
    class="resizable-panel" :class="[className]"
    :style="containerStyle"
    :data-direction="effectiveDirection"
    :data-dragging="isDragging"
  >
    <div class="resizable-panel-first" :class="[firstPanelClassName]" :style="firstPanelStyle">
      <slot name="first" />
    </div>
    <div
      class="resizable-panel-resizer" :class="[resizerClassName]"
      :style="resizerStyle"
      role="separator"
      :aria-orientation="isHorizontal ? 'vertical' : 'horizontal'"
      :aria-valuenow="Math.round(size)"
      :aria-valuemin="minSize"
      :aria-valuemax="maxSize"
      tabindex="0"
      @mousedown="handleMouseDown"
      @touchstart="handleTouchStart"
    >
      <div class="resizable-panel-resizer-line" />
    </div>
    <div class="resizable-panel-second" :class="[secondPanelClassName]" :style="secondPanelStyle">
      <slot name="second" />
    </div>
  </div>
</template>
